### ISSUE TITLE
Cannot move vertically after resize

### ISSUE THREAD

**Issue by infinia-yzl** [FeliciousX/simple-vanilla-pictograph-editor#4]
After resizing to the smallest size possible (using vertical or diagonal resize), the chart cannot be moved vertically (only can be moved horizontally).

**Comment by FeliciousX** [comment]
:disappointed:  okay thanks. I didn't notice it. Apparently if you deselect and reselect it will be fine. Will check it out.

**Comment by FeliciousX** [comment]
:P not maintaining anymore
